/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
/**
 * CovidContinent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class CovidContinent {
  @SerializedName("updated")
  private BigDecimal updated = null;

  @SerializedName("cases")
  private BigDecimal cases = null;

  @SerializedName("todayCases")
  private BigDecimal todayCases = null;

  @SerializedName("deaths")
  private BigDecimal deaths = null;

  @SerializedName("todayDeaths")
  private BigDecimal todayDeaths = null;

  @SerializedName("recovered")
  private BigDecimal recovered = null;

  @SerializedName("todayRecovered")
  private BigDecimal todayRecovered = null;

  @SerializedName("active")
  private BigDecimal active = null;

  @SerializedName("critical")
  private BigDecimal critical = null;

  @SerializedName("casesPerOneMillion")
  private BigDecimal casesPerOneMillion = null;

  @SerializedName("deathsPerOneMillion")
  private BigDecimal deathsPerOneMillion = null;

  @SerializedName("tests")
  private BigDecimal tests = null;

  @SerializedName("testsPerOneMillion")
  private BigDecimal testsPerOneMillion = null;

  @SerializedName("population")
  private BigDecimal population = null;

  @SerializedName("continent")
  private String continent = null;

  @SerializedName("activePerOneMillion")
  private BigDecimal activePerOneMillion = null;

  @SerializedName("recoveredPerOneMillion")
  private BigDecimal recoveredPerOneMillion = null;

  @SerializedName("criticalPerOneMillion")
  private BigDecimal criticalPerOneMillion = null;

  @SerializedName("continentInfo")
  private CovidContinentContinentInfo continentInfo = null;

  @SerializedName("countries")
  private java.util.List<String> countries = null;

  public CovidContinent updated(BigDecimal updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @Schema(description = "")
  public BigDecimal getUpdated() {
    return updated;
  }

  public void setUpdated(BigDecimal updated) {
    this.updated = updated;
  }

  public CovidContinent cases(BigDecimal cases) {
    this.cases = cases;
    return this;
  }

   /**
   * Get cases
   * @return cases
  **/
  @Schema(description = "")
  public BigDecimal getCases() {
    return cases;
  }

  public void setCases(BigDecimal cases) {
    this.cases = cases;
  }

  public CovidContinent todayCases(BigDecimal todayCases) {
    this.todayCases = todayCases;
    return this;
  }

   /**
   * Get todayCases
   * @return todayCases
  **/
  @Schema(description = "")
  public BigDecimal getTodayCases() {
    return todayCases;
  }

  public void setTodayCases(BigDecimal todayCases) {
    this.todayCases = todayCases;
  }

  public CovidContinent deaths(BigDecimal deaths) {
    this.deaths = deaths;
    return this;
  }

   /**
   * Get deaths
   * @return deaths
  **/
  @Schema(description = "")
  public BigDecimal getDeaths() {
    return deaths;
  }

  public void setDeaths(BigDecimal deaths) {
    this.deaths = deaths;
  }

  public CovidContinent todayDeaths(BigDecimal todayDeaths) {
    this.todayDeaths = todayDeaths;
    return this;
  }

   /**
   * Get todayDeaths
   * @return todayDeaths
  **/
  @Schema(description = "")
  public BigDecimal getTodayDeaths() {
    return todayDeaths;
  }

  public void setTodayDeaths(BigDecimal todayDeaths) {
    this.todayDeaths = todayDeaths;
  }

  public CovidContinent recovered(BigDecimal recovered) {
    this.recovered = recovered;
    return this;
  }

   /**
   * Get recovered
   * @return recovered
  **/
  @Schema(description = "")
  public BigDecimal getRecovered() {
    return recovered;
  }

  public void setRecovered(BigDecimal recovered) {
    this.recovered = recovered;
  }

  public CovidContinent todayRecovered(BigDecimal todayRecovered) {
    this.todayRecovered = todayRecovered;
    return this;
  }

   /**
   * Get todayRecovered
   * @return todayRecovered
  **/
  @Schema(description = "")
  public BigDecimal getTodayRecovered() {
    return todayRecovered;
  }

  public void setTodayRecovered(BigDecimal todayRecovered) {
    this.todayRecovered = todayRecovered;
  }

  public CovidContinent active(BigDecimal active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @Schema(description = "")
  public BigDecimal getActive() {
    return active;
  }

  public void setActive(BigDecimal active) {
    this.active = active;
  }

  public CovidContinent critical(BigDecimal critical) {
    this.critical = critical;
    return this;
  }

   /**
   * Get critical
   * @return critical
  **/
  @Schema(description = "")
  public BigDecimal getCritical() {
    return critical;
  }

  public void setCritical(BigDecimal critical) {
    this.critical = critical;
  }

  public CovidContinent casesPerOneMillion(BigDecimal casesPerOneMillion) {
    this.casesPerOneMillion = casesPerOneMillion;
    return this;
  }

   /**
   * Get casesPerOneMillion
   * @return casesPerOneMillion
  **/
  @Schema(description = "")
  public BigDecimal getCasesPerOneMillion() {
    return casesPerOneMillion;
  }

  public void setCasesPerOneMillion(BigDecimal casesPerOneMillion) {
    this.casesPerOneMillion = casesPerOneMillion;
  }

  public CovidContinent deathsPerOneMillion(BigDecimal deathsPerOneMillion) {
    this.deathsPerOneMillion = deathsPerOneMillion;
    return this;
  }

   /**
   * Get deathsPerOneMillion
   * @return deathsPerOneMillion
  **/
  @Schema(description = "")
  public BigDecimal getDeathsPerOneMillion() {
    return deathsPerOneMillion;
  }

  public void setDeathsPerOneMillion(BigDecimal deathsPerOneMillion) {
    this.deathsPerOneMillion = deathsPerOneMillion;
  }

  public CovidContinent tests(BigDecimal tests) {
    this.tests = tests;
    return this;
  }

   /**
   * Get tests
   * @return tests
  **/
  @Schema(description = "")
  public BigDecimal getTests() {
    return tests;
  }

  public void setTests(BigDecimal tests) {
    this.tests = tests;
  }

  public CovidContinent testsPerOneMillion(BigDecimal testsPerOneMillion) {
    this.testsPerOneMillion = testsPerOneMillion;
    return this;
  }

   /**
   * Get testsPerOneMillion
   * @return testsPerOneMillion
  **/
  @Schema(description = "")
  public BigDecimal getTestsPerOneMillion() {
    return testsPerOneMillion;
  }

  public void setTestsPerOneMillion(BigDecimal testsPerOneMillion) {
    this.testsPerOneMillion = testsPerOneMillion;
  }

  public CovidContinent population(BigDecimal population) {
    this.population = population;
    return this;
  }

   /**
   * Get population
   * @return population
  **/
  @Schema(description = "")
  public BigDecimal getPopulation() {
    return population;
  }

  public void setPopulation(BigDecimal population) {
    this.population = population;
  }

  public CovidContinent continent(String continent) {
    this.continent = continent;
    return this;
  }

   /**
   * Get continent
   * @return continent
  **/
  @Schema(description = "")
  public String getContinent() {
    return continent;
  }

  public void setContinent(String continent) {
    this.continent = continent;
  }

  public CovidContinent activePerOneMillion(BigDecimal activePerOneMillion) {
    this.activePerOneMillion = activePerOneMillion;
    return this;
  }

   /**
   * Get activePerOneMillion
   * @return activePerOneMillion
  **/
  @Schema(description = "")
  public BigDecimal getActivePerOneMillion() {
    return activePerOneMillion;
  }

  public void setActivePerOneMillion(BigDecimal activePerOneMillion) {
    this.activePerOneMillion = activePerOneMillion;
  }

  public CovidContinent recoveredPerOneMillion(BigDecimal recoveredPerOneMillion) {
    this.recoveredPerOneMillion = recoveredPerOneMillion;
    return this;
  }

   /**
   * Get recoveredPerOneMillion
   * @return recoveredPerOneMillion
  **/
  @Schema(description = "")
  public BigDecimal getRecoveredPerOneMillion() {
    return recoveredPerOneMillion;
  }

  public void setRecoveredPerOneMillion(BigDecimal recoveredPerOneMillion) {
    this.recoveredPerOneMillion = recoveredPerOneMillion;
  }

  public CovidContinent criticalPerOneMillion(BigDecimal criticalPerOneMillion) {
    this.criticalPerOneMillion = criticalPerOneMillion;
    return this;
  }

   /**
   * Get criticalPerOneMillion
   * @return criticalPerOneMillion
  **/
  @Schema(description = "")
  public BigDecimal getCriticalPerOneMillion() {
    return criticalPerOneMillion;
  }

  public void setCriticalPerOneMillion(BigDecimal criticalPerOneMillion) {
    this.criticalPerOneMillion = criticalPerOneMillion;
  }

  public CovidContinent continentInfo(CovidContinentContinentInfo continentInfo) {
    this.continentInfo = continentInfo;
    return this;
  }

   /**
   * Get continentInfo
   * @return continentInfo
  **/
  @Schema(description = "")
  public CovidContinentContinentInfo getContinentInfo() {
    return continentInfo;
  }

  public void setContinentInfo(CovidContinentContinentInfo continentInfo) {
    this.continentInfo = continentInfo;
  }

  public CovidContinent countries(java.util.List<String> countries) {
    this.countries = countries;
    return this;
  }

  public CovidContinent addCountriesItem(String countriesItem) {
    if (this.countries == null) {
      this.countries = new java.util.ArrayList<>();
    }
    this.countries.add(countriesItem);
    return this;
  }

   /**
   * Get countries
   * @return countries
  **/
  @Schema(description = "")
  public java.util.List<String> getCountries() {
    return countries;
  }

  public void setCountries(java.util.List<String> countries) {
    this.countries = countries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CovidContinent covidContinent = (CovidContinent) o;
    return Objects.equals(this.updated, covidContinent.updated) &&
        Objects.equals(this.cases, covidContinent.cases) &&
        Objects.equals(this.todayCases, covidContinent.todayCases) &&
        Objects.equals(this.deaths, covidContinent.deaths) &&
        Objects.equals(this.todayDeaths, covidContinent.todayDeaths) &&
        Objects.equals(this.recovered, covidContinent.recovered) &&
        Objects.equals(this.todayRecovered, covidContinent.todayRecovered) &&
        Objects.equals(this.active, covidContinent.active) &&
        Objects.equals(this.critical, covidContinent.critical) &&
        Objects.equals(this.casesPerOneMillion, covidContinent.casesPerOneMillion) &&
        Objects.equals(this.deathsPerOneMillion, covidContinent.deathsPerOneMillion) &&
        Objects.equals(this.tests, covidContinent.tests) &&
        Objects.equals(this.testsPerOneMillion, covidContinent.testsPerOneMillion) &&
        Objects.equals(this.population, covidContinent.population) &&
        Objects.equals(this.continent, covidContinent.continent) &&
        Objects.equals(this.activePerOneMillion, covidContinent.activePerOneMillion) &&
        Objects.equals(this.recoveredPerOneMillion, covidContinent.recoveredPerOneMillion) &&
        Objects.equals(this.criticalPerOneMillion, covidContinent.criticalPerOneMillion) &&
        Objects.equals(this.continentInfo, covidContinent.continentInfo) &&
        Objects.equals(this.countries, covidContinent.countries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(updated, cases, todayCases, deaths, todayDeaths, recovered, todayRecovered, active, critical, casesPerOneMillion, deathsPerOneMillion, tests, testsPerOneMillion, population, continent, activePerOneMillion, recoveredPerOneMillion, criticalPerOneMillion, continentInfo, countries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CovidContinent {\n");
    
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    cases: ").append(toIndentedString(cases)).append("\n");
    sb.append("    todayCases: ").append(toIndentedString(todayCases)).append("\n");
    sb.append("    deaths: ").append(toIndentedString(deaths)).append("\n");
    sb.append("    todayDeaths: ").append(toIndentedString(todayDeaths)).append("\n");
    sb.append("    recovered: ").append(toIndentedString(recovered)).append("\n");
    sb.append("    todayRecovered: ").append(toIndentedString(todayRecovered)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    critical: ").append(toIndentedString(critical)).append("\n");
    sb.append("    casesPerOneMillion: ").append(toIndentedString(casesPerOneMillion)).append("\n");
    sb.append("    deathsPerOneMillion: ").append(toIndentedString(deathsPerOneMillion)).append("\n");
    sb.append("    tests: ").append(toIndentedString(tests)).append("\n");
    sb.append("    testsPerOneMillion: ").append(toIndentedString(testsPerOneMillion)).append("\n");
    sb.append("    population: ").append(toIndentedString(population)).append("\n");
    sb.append("    continent: ").append(toIndentedString(continent)).append("\n");
    sb.append("    activePerOneMillion: ").append(toIndentedString(activePerOneMillion)).append("\n");
    sb.append("    recoveredPerOneMillion: ").append(toIndentedString(recoveredPerOneMillion)).append("\n");
    sb.append("    criticalPerOneMillion: ").append(toIndentedString(criticalPerOneMillion)).append("\n");
    sb.append("    continentInfo: ").append(toIndentedString(continentInfo)).append("\n");
    sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
