/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CovidHistoricalUSCountyInner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class CovidHistoricalUSCountyInner {
  @SerializedName("province")
  private String province = null;

  @SerializedName("county")
  private String county = null;

  @SerializedName("timeline")
  private Object timeline = null;

  public CovidHistoricalUSCountyInner province(String province) {
    this.province = province;
    return this;
  }

   /**
   * Get province
   * @return province
  **/
  @Schema(description = "")
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public CovidHistoricalUSCountyInner county(String county) {
    this.county = county;
    return this;
  }

   /**
   * Get county
   * @return county
  **/
  @Schema(description = "")
  public String getCounty() {
    return county;
  }

  public void setCounty(String county) {
    this.county = county;
  }

  public CovidHistoricalUSCountyInner timeline(Object timeline) {
    this.timeline = timeline;
    return this;
  }

   /**
   * The amount of key-value pairs in &#x27;cases&#x27;, &#x27;deaths&#x27; and &#x27;recovered&#x27; is dependent on the &#x27;lastdays&#x27; query
   * @return timeline
  **/
  @Schema(description = "The amount of key-value pairs in 'cases', 'deaths' and 'recovered' is dependent on the 'lastdays' query")
  public Object getTimeline() {
    return timeline;
  }

  public void setTimeline(Object timeline) {
    this.timeline = timeline;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CovidHistoricalUSCountyInner covidHistoricalUSCountyInner = (CovidHistoricalUSCountyInner) o;
    return Objects.equals(this.province, covidHistoricalUSCountyInner.province) &&
        Objects.equals(this.county, covidHistoricalUSCountyInner.county) &&
        Objects.equals(this.timeline, covidHistoricalUSCountyInner.timeline);
  }

  @Override
  public int hashCode() {
    return Objects.hash(province, county, timeline);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CovidHistoricalUSCountyInner {\n");
    
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("    county: ").append(toIndentedString(county)).append("\n");
    sb.append("    timeline: ").append(toIndentedString(timeline)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
