/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
/**
 * CovidJHUCountriesStats
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class CovidJHUCountriesStats {
  @SerializedName("confirmed")
  private BigDecimal confirmed = null;

  @SerializedName("deaths")
  private BigDecimal deaths = null;

  @SerializedName("recovered")
  private BigDecimal recovered = null;

  public CovidJHUCountriesStats confirmed(BigDecimal confirmed) {
    this.confirmed = confirmed;
    return this;
  }

   /**
   * Get confirmed
   * @return confirmed
  **/
  @Schema(description = "")
  public BigDecimal getConfirmed() {
    return confirmed;
  }

  public void setConfirmed(BigDecimal confirmed) {
    this.confirmed = confirmed;
  }

  public CovidJHUCountriesStats deaths(BigDecimal deaths) {
    this.deaths = deaths;
    return this;
  }

   /**
   * Get deaths
   * @return deaths
  **/
  @Schema(description = "")
  public BigDecimal getDeaths() {
    return deaths;
  }

  public void setDeaths(BigDecimal deaths) {
    this.deaths = deaths;
  }

  public CovidJHUCountriesStats recovered(BigDecimal recovered) {
    this.recovered = recovered;
    return this;
  }

   /**
   * Get recovered
   * @return recovered
  **/
  @Schema(description = "")
  public BigDecimal getRecovered() {
    return recovered;
  }

  public void setRecovered(BigDecimal recovered) {
    this.recovered = recovered;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CovidJHUCountriesStats covidJHUCountriesStats = (CovidJHUCountriesStats) o;
    return Objects.equals(this.confirmed, covidJHUCountriesStats.confirmed) &&
        Objects.equals(this.deaths, covidJHUCountriesStats.deaths) &&
        Objects.equals(this.recovered, covidJHUCountriesStats.recovered);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmed, deaths, recovered);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CovidJHUCountriesStats {\n");
    
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    deaths: ").append(toIndentedString(deaths)).append("\n");
    sb.append("    recovered: ").append(toIndentedString(recovered)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
