/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * The amount of key-value pairs in &#x27;cases&#x27;, &#x27;deaths&#x27; and &#x27;recovered&#x27; is dependent on the &#x27;lastdays&#x27; query
 */
@Schema(description = "The amount of key-value pairs in 'cases', 'deaths' and 'recovered' is dependent on the 'lastdays' query")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class CovidHistoricalAll {
  @SerializedName("cases")
  private CovidHistoricalAllCases cases = null;

  @SerializedName("deaths")
  private CovidHistoricalAllCases deaths = null;

  @SerializedName("recovered")
  private CovidHistoricalAllCases recovered = null;

  public CovidHistoricalAll cases(CovidHistoricalAllCases cases) {
    this.cases = cases;
    return this;
  }

   /**
   * Get cases
   * @return cases
  **/
  @Schema(description = "")
  public CovidHistoricalAllCases getCases() {
    return cases;
  }

  public void setCases(CovidHistoricalAllCases cases) {
    this.cases = cases;
  }

  public CovidHistoricalAll deaths(CovidHistoricalAllCases deaths) {
    this.deaths = deaths;
    return this;
  }

   /**
   * Get deaths
   * @return deaths
  **/
  @Schema(description = "")
  public CovidHistoricalAllCases getDeaths() {
    return deaths;
  }

  public void setDeaths(CovidHistoricalAllCases deaths) {
    this.deaths = deaths;
  }

  public CovidHistoricalAll recovered(CovidHistoricalAllCases recovered) {
    this.recovered = recovered;
    return this;
  }

   /**
   * Get recovered
   * @return recovered
  **/
  @Schema(description = "")
  public CovidHistoricalAllCases getRecovered() {
    return recovered;
  }

  public void setRecovered(CovidHistoricalAllCases recovered) {
    this.recovered = recovered;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CovidHistoricalAll covidHistoricalAll = (CovidHistoricalAll) o;
    return Objects.equals(this.cases, covidHistoricalAll.cases) &&
        Objects.equals(this.deaths, covidHistoricalAll.deaths) &&
        Objects.equals(this.recovered, covidHistoricalAll.recovered);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cases, deaths, recovered);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CovidHistoricalAll {\n");
    
    sb.append("    cases: ").append(toIndentedString(cases)).append("\n");
    sb.append("    deaths: ").append(toIndentedString(deaths)).append("\n");
    sb.append("    recovered: ").append(toIndentedString(recovered)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
