/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
/**
 * CovidCountryCountryInfo
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class CovidCountryCountryInfo {
  @SerializedName("_id")
  private BigDecimal _id = null;

  @SerializedName("iso2")
  private String iso2 = null;

  @SerializedName("iso3")
  private String iso3 = null;

  @SerializedName("lat")
  private BigDecimal lat = null;

  @SerializedName("long")
  private BigDecimal _long = null;

  @SerializedName("flag")
  private String flag = null;

  public CovidCountryCountryInfo _id(BigDecimal _id) {
    this._id = _id;
    return this;
  }

   /**
   * Get _id
   * @return _id
  **/
  @Schema(description = "")
  public BigDecimal getId() {
    return _id;
  }

  public void setId(BigDecimal _id) {
    this._id = _id;
  }

  public CovidCountryCountryInfo iso2(String iso2) {
    this.iso2 = iso2;
    return this;
  }

   /**
   * Get iso2
   * @return iso2
  **/
  @Schema(description = "")
  public String getIso2() {
    return iso2;
  }

  public void setIso2(String iso2) {
    this.iso2 = iso2;
  }

  public CovidCountryCountryInfo iso3(String iso3) {
    this.iso3 = iso3;
    return this;
  }

   /**
   * Get iso3
   * @return iso3
  **/
  @Schema(description = "")
  public String getIso3() {
    return iso3;
  }

  public void setIso3(String iso3) {
    this.iso3 = iso3;
  }

  public CovidCountryCountryInfo lat(BigDecimal lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Get lat
   * @return lat
  **/
  @Schema(description = "")
  public BigDecimal getLat() {
    return lat;
  }

  public void setLat(BigDecimal lat) {
    this.lat = lat;
  }

  public CovidCountryCountryInfo _long(BigDecimal _long) {
    this._long = _long;
    return this;
  }

   /**
   * Get _long
   * @return _long
  **/
  @Schema(description = "")
  public BigDecimal getLong() {
    return _long;
  }

  public void setLong(BigDecimal _long) {
    this._long = _long;
  }

  public CovidCountryCountryInfo flag(String flag) {
    this.flag = flag;
    return this;
  }

   /**
   * Get flag
   * @return flag
  **/
  @Schema(description = "")
  public String getFlag() {
    return flag;
  }

  public void setFlag(String flag) {
    this.flag = flag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CovidCountryCountryInfo covidCountryCountryInfo = (CovidCountryCountryInfo) o;
    return Objects.equals(this._id, covidCountryCountryInfo._id) &&
        Objects.equals(this.iso2, covidCountryCountryInfo.iso2) &&
        Objects.equals(this.iso3, covidCountryCountryInfo.iso3) &&
        Objects.equals(this.lat, covidCountryCountryInfo.lat) &&
        Objects.equals(this._long, covidCountryCountryInfo._long) &&
        Objects.equals(this.flag, covidCountryCountryInfo.flag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_id, iso2, iso3, lat, _long, flag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CovidCountryCountryInfo {\n");
    
    sb.append("    _id: ").append(toIndentedString(_id)).append("\n");
    sb.append("    iso2: ").append(toIndentedString(iso2)).append("\n");
    sb.append("    iso3: ").append(toIndentedString(iso3)).append("\n");
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    _long: ").append(toIndentedString(_long)).append("\n");
    sb.append("    flag: ").append(toIndentedString(flag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
