/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CovidAppleSubregions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class CovidAppleSubregions {
  @SerializedName("country")
  private String country = null;

  @SerializedName("subregions")
  private java.util.List<String> subregions = null;

  public CovidAppleSubregions country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @Schema(description = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public CovidAppleSubregions subregions(java.util.List<String> subregions) {
    this.subregions = subregions;
    return this;
  }

  public CovidAppleSubregions addSubregionsItem(String subregionsItem) {
    if (this.subregions == null) {
      this.subregions = new java.util.ArrayList<>();
    }
    this.subregions.add(subregionsItem);
    return this;
  }

   /**
   * Get subregions
   * @return subregions
  **/
  @Schema(description = "")
  public java.util.List<String> getSubregions() {
    return subregions;
  }

  public void setSubregions(java.util.List<String> subregions) {
    this.subregions = subregions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CovidAppleSubregions covidAppleSubregions = (CovidAppleSubregions) o;
    return Objects.equals(this.country, covidAppleSubregions.country) &&
        Objects.equals(this.subregions, covidAppleSubregions.subregions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, subregions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CovidAppleSubregions {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    subregions: ").append(toIndentedString(subregions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
