/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CovidJHUCountries
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class CovidJHUCountries {
  @SerializedName("country")
  private String country = null;

  @SerializedName("county")
  private String county = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  @SerializedName("stats")
  private CovidJHUCountriesStats stats = null;

  @SerializedName("coordinates")
  private CovidJHUCountriesCoordinates coordinates = null;

  @SerializedName("province")
  private String province = null;

  public CovidJHUCountries country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @Schema(description = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public CovidJHUCountries county(String county) {
    this.county = county;
    return this;
  }

   /**
   * Get county
   * @return county
  **/
  @Schema(description = "")
  public String getCounty() {
    return county;
  }

  public void setCounty(String county) {
    this.county = county;
  }

  public CovidJHUCountries updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @Schema(description = "")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }

  public CovidJHUCountries stats(CovidJHUCountriesStats stats) {
    this.stats = stats;
    return this;
  }

   /**
   * Get stats
   * @return stats
  **/
  @Schema(description = "")
  public CovidJHUCountriesStats getStats() {
    return stats;
  }

  public void setStats(CovidJHUCountriesStats stats) {
    this.stats = stats;
  }

  public CovidJHUCountries coordinates(CovidJHUCountriesCoordinates coordinates) {
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @Schema(description = "")
  public CovidJHUCountriesCoordinates getCoordinates() {
    return coordinates;
  }

  public void setCoordinates(CovidJHUCountriesCoordinates coordinates) {
    this.coordinates = coordinates;
  }

  public CovidJHUCountries province(String province) {
    this.province = province;
    return this;
  }

   /**
   * Get province
   * @return province
  **/
  @Schema(description = "")
  public String getProvince() {
    return province;
  }

  public void setProvince(String province) {
    this.province = province;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CovidJHUCountries covidJHUCountries = (CovidJHUCountries) o;
    return Objects.equals(this.country, covidJHUCountries.country) &&
        Objects.equals(this.county, covidJHUCountries.county) &&
        Objects.equals(this.updatedAt, covidJHUCountries.updatedAt) &&
        Objects.equals(this.stats, covidJHUCountries.stats) &&
        Objects.equals(this.coordinates, covidJHUCountries.coordinates) &&
        Objects.equals(this.province, covidJHUCountries.province);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, county, updatedAt, stats, coordinates, province);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CovidJHUCountries {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    county: ").append(toIndentedString(county)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    province: ").append(toIndentedString(province)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
