/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Therapeutic
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class Therapeutic {
  @SerializedName("medicationClass")
  private String medicationClass = null;

  @SerializedName("tradeName")
  private java.util.List<String> tradeName = null;

  @SerializedName("details")
  private String details = null;

  @SerializedName("developerResearcher")
  private java.util.List<String> developerResearcher = null;

  @SerializedName("sponsors")
  private java.util.List<String> sponsors = null;

  @SerializedName("trialPhase")
  private String trialPhase = null;

  @SerializedName("lastUpdate")
  private String lastUpdate = null;

  public Therapeutic medicationClass(String medicationClass) {
    this.medicationClass = medicationClass;
    return this;
  }

   /**
   * Get medicationClass
   * @return medicationClass
  **/
  @Schema(description = "")
  public String getMedicationClass() {
    return medicationClass;
  }

  public void setMedicationClass(String medicationClass) {
    this.medicationClass = medicationClass;
  }

  public Therapeutic tradeName(java.util.List<String> tradeName) {
    this.tradeName = tradeName;
    return this;
  }

  public Therapeutic addTradeNameItem(String tradeNameItem) {
    if (this.tradeName == null) {
      this.tradeName = new java.util.ArrayList<>();
    }
    this.tradeName.add(tradeNameItem);
    return this;
  }

   /**
   * Get tradeName
   * @return tradeName
  **/
  @Schema(description = "")
  public java.util.List<String> getTradeName() {
    return tradeName;
  }

  public void setTradeName(java.util.List<String> tradeName) {
    this.tradeName = tradeName;
  }

  public Therapeutic details(String details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @Schema(description = "")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }

  public Therapeutic developerResearcher(java.util.List<String> developerResearcher) {
    this.developerResearcher = developerResearcher;
    return this;
  }

  public Therapeutic addDeveloperResearcherItem(String developerResearcherItem) {
    if (this.developerResearcher == null) {
      this.developerResearcher = new java.util.ArrayList<>();
    }
    this.developerResearcher.add(developerResearcherItem);
    return this;
  }

   /**
   * Get developerResearcher
   * @return developerResearcher
  **/
  @Schema(description = "")
  public java.util.List<String> getDeveloperResearcher() {
    return developerResearcher;
  }

  public void setDeveloperResearcher(java.util.List<String> developerResearcher) {
    this.developerResearcher = developerResearcher;
  }

  public Therapeutic sponsors(java.util.List<String> sponsors) {
    this.sponsors = sponsors;
    return this;
  }

  public Therapeutic addSponsorsItem(String sponsorsItem) {
    if (this.sponsors == null) {
      this.sponsors = new java.util.ArrayList<>();
    }
    this.sponsors.add(sponsorsItem);
    return this;
  }

   /**
   * Get sponsors
   * @return sponsors
  **/
  @Schema(description = "")
  public java.util.List<String> getSponsors() {
    return sponsors;
  }

  public void setSponsors(java.util.List<String> sponsors) {
    this.sponsors = sponsors;
  }

  public Therapeutic trialPhase(String trialPhase) {
    this.trialPhase = trialPhase;
    return this;
  }

   /**
   * Get trialPhase
   * @return trialPhase
  **/
  @Schema(description = "")
  public String getTrialPhase() {
    return trialPhase;
  }

  public void setTrialPhase(String trialPhase) {
    this.trialPhase = trialPhase;
  }

  public Therapeutic lastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

   /**
   * Get lastUpdate
   * @return lastUpdate
  **/
  @Schema(description = "")
  public String getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Therapeutic therapeutic = (Therapeutic) o;
    return Objects.equals(this.medicationClass, therapeutic.medicationClass) &&
        Objects.equals(this.tradeName, therapeutic.tradeName) &&
        Objects.equals(this.details, therapeutic.details) &&
        Objects.equals(this.developerResearcher, therapeutic.developerResearcher) &&
        Objects.equals(this.sponsors, therapeutic.sponsors) &&
        Objects.equals(this.trialPhase, therapeutic.trialPhase) &&
        Objects.equals(this.lastUpdate, therapeutic.lastUpdate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(medicationClass, tradeName, details, developerResearcher, sponsors, trialPhase, lastUpdate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Therapeutic {\n");
    
    sb.append("    medicationClass: ").append(toIndentedString(medicationClass)).append("\n");
    sb.append("    tradeName: ").append(toIndentedString(tradeName)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    developerResearcher: ").append(toIndentedString(developerResearcher)).append("\n");
    sb.append("    sponsors: ").append(toIndentedString(sponsors)).append("\n");
    sb.append("    trialPhase: ").append(toIndentedString(trialPhase)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
