/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.math.BigDecimal;
/**
 * USCL
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class USCL {
  @SerializedName("week")
  private String week = null;

  @SerializedName("totalA")
  private BigDecimal totalA = null;

  @SerializedName("totalB")
  private BigDecimal totalB = null;

  @SerializedName("percentPositiveA")
  private BigDecimal percentPositiveA = null;

  @SerializedName("percentPositiveB")
  private BigDecimal percentPositiveB = null;

  @SerializedName("totalTests")
  private BigDecimal totalTests = null;

  @SerializedName("percentPositive")
  private BigDecimal percentPositive = null;

  public USCL week(String week) {
    this.week = week;
    return this;
  }

   /**
   * Get week
   * @return week
  **/
  @Schema(description = "")
  public String getWeek() {
    return week;
  }

  public void setWeek(String week) {
    this.week = week;
  }

  public USCL totalA(BigDecimal totalA) {
    this.totalA = totalA;
    return this;
  }

   /**
   * Get totalA
   * @return totalA
  **/
  @Schema(description = "")
  public BigDecimal getTotalA() {
    return totalA;
  }

  public void setTotalA(BigDecimal totalA) {
    this.totalA = totalA;
  }

  public USCL totalB(BigDecimal totalB) {
    this.totalB = totalB;
    return this;
  }

   /**
   * Get totalB
   * @return totalB
  **/
  @Schema(description = "")
  public BigDecimal getTotalB() {
    return totalB;
  }

  public void setTotalB(BigDecimal totalB) {
    this.totalB = totalB;
  }

  public USCL percentPositiveA(BigDecimal percentPositiveA) {
    this.percentPositiveA = percentPositiveA;
    return this;
  }

   /**
   * Get percentPositiveA
   * @return percentPositiveA
  **/
  @Schema(description = "")
  public BigDecimal getPercentPositiveA() {
    return percentPositiveA;
  }

  public void setPercentPositiveA(BigDecimal percentPositiveA) {
    this.percentPositiveA = percentPositiveA;
  }

  public USCL percentPositiveB(BigDecimal percentPositiveB) {
    this.percentPositiveB = percentPositiveB;
    return this;
  }

   /**
   * Get percentPositiveB
   * @return percentPositiveB
  **/
  @Schema(description = "")
  public BigDecimal getPercentPositiveB() {
    return percentPositiveB;
  }

  public void setPercentPositiveB(BigDecimal percentPositiveB) {
    this.percentPositiveB = percentPositiveB;
  }

  public USCL totalTests(BigDecimal totalTests) {
    this.totalTests = totalTests;
    return this;
  }

   /**
   * Get totalTests
   * @return totalTests
  **/
  @Schema(description = "")
  public BigDecimal getTotalTests() {
    return totalTests;
  }

  public void setTotalTests(BigDecimal totalTests) {
    this.totalTests = totalTests;
  }

  public USCL percentPositive(BigDecimal percentPositive) {
    this.percentPositive = percentPositive;
    return this;
  }

   /**
   * Get percentPositive
   * @return percentPositive
  **/
  @Schema(description = "")
  public BigDecimal getPercentPositive() {
    return percentPositive;
  }

  public void setPercentPositive(BigDecimal percentPositive) {
    this.percentPositive = percentPositive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    USCL USCL = (USCL) o;
    return Objects.equals(this.week, USCL.week) &&
        Objects.equals(this.totalA, USCL.totalA) &&
        Objects.equals(this.totalB, USCL.totalB) &&
        Objects.equals(this.percentPositiveA, USCL.percentPositiveA) &&
        Objects.equals(this.percentPositiveB, USCL.percentPositiveB) &&
        Objects.equals(this.totalTests, USCL.totalTests) &&
        Objects.equals(this.percentPositive, USCL.percentPositive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(week, totalA, totalB, percentPositiveA, percentPositiveB, totalTests, percentPositive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class USCL {\n");
    
    sb.append("    week: ").append(toIndentedString(week)).append("\n");
    sb.append("    totalA: ").append(toIndentedString(totalA)).append("\n");
    sb.append("    totalB: ").append(toIndentedString(totalB)).append("\n");
    sb.append("    percentPositiveA: ").append(toIndentedString(percentPositiveA)).append("\n");
    sb.append("    percentPositiveB: ").append(toIndentedString(percentPositiveB)).append("\n");
    sb.append("    totalTests: ").append(toIndentedString(totalTests)).append("\n");
    sb.append("    percentPositive: ").append(toIndentedString(percentPositive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
