/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Vaccine
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class Vaccine {
  @SerializedName("candidate")
  private String candidate = null;

  @SerializedName("mechanism")
  private String mechanism = null;

  @SerializedName("sponsors")
  private java.util.List<String> sponsors = null;

  @SerializedName("details")
  private String details = null;

  @SerializedName("trialPhase")
  private String trialPhase = null;

  @SerializedName("institutions")
  private java.util.List<String> institutions = null;

  public Vaccine candidate(String candidate) {
    this.candidate = candidate;
    return this;
  }

   /**
   * Get candidate
   * @return candidate
  **/
  @Schema(description = "")
  public String getCandidate() {
    return candidate;
  }

  public void setCandidate(String candidate) {
    this.candidate = candidate;
  }

  public Vaccine mechanism(String mechanism) {
    this.mechanism = mechanism;
    return this;
  }

   /**
   * Get mechanism
   * @return mechanism
  **/
  @Schema(description = "")
  public String getMechanism() {
    return mechanism;
  }

  public void setMechanism(String mechanism) {
    this.mechanism = mechanism;
  }

  public Vaccine sponsors(java.util.List<String> sponsors) {
    this.sponsors = sponsors;
    return this;
  }

  public Vaccine addSponsorsItem(String sponsorsItem) {
    if (this.sponsors == null) {
      this.sponsors = new java.util.ArrayList<>();
    }
    this.sponsors.add(sponsorsItem);
    return this;
  }

   /**
   * Get sponsors
   * @return sponsors
  **/
  @Schema(description = "")
  public java.util.List<String> getSponsors() {
    return sponsors;
  }

  public void setSponsors(java.util.List<String> sponsors) {
    this.sponsors = sponsors;
  }

  public Vaccine details(String details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @Schema(description = "")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }

  public Vaccine trialPhase(String trialPhase) {
    this.trialPhase = trialPhase;
    return this;
  }

   /**
   * Get trialPhase
   * @return trialPhase
  **/
  @Schema(description = "")
  public String getTrialPhase() {
    return trialPhase;
  }

  public void setTrialPhase(String trialPhase) {
    this.trialPhase = trialPhase;
  }

  public Vaccine institutions(java.util.List<String> institutions) {
    this.institutions = institutions;
    return this;
  }

  public Vaccine addInstitutionsItem(String institutionsItem) {
    if (this.institutions == null) {
      this.institutions = new java.util.ArrayList<>();
    }
    this.institutions.add(institutionsItem);
    return this;
  }

   /**
   * Get institutions
   * @return institutions
  **/
  @Schema(description = "")
  public java.util.List<String> getInstitutions() {
    return institutions;
  }

  public void setInstitutions(java.util.List<String> institutions) {
    this.institutions = institutions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vaccine vaccine = (Vaccine) o;
    return Objects.equals(this.candidate, vaccine.candidate) &&
        Objects.equals(this.mechanism, vaccine.mechanism) &&
        Objects.equals(this.sponsors, vaccine.sponsors) &&
        Objects.equals(this.details, vaccine.details) &&
        Objects.equals(this.trialPhase, vaccine.trialPhase) &&
        Objects.equals(this.institutions, vaccine.institutions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(candidate, mechanism, sponsors, details, trialPhase, institutions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vaccine {\n");
    
    sb.append("    candidate: ").append(toIndentedString(candidate)).append("\n");
    sb.append("    mechanism: ").append(toIndentedString(mechanism)).append("\n");
    sb.append("    sponsors: ").append(toIndentedString(sponsors)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    trialPhase: ").append(toIndentedString(trialPhase)).append("\n");
    sb.append("    institutions: ").append(toIndentedString(institutions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
