/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * VaccineCountriesCoverageInner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class VaccineCountriesCoverageInner {
  @SerializedName("country")
  private String country = null;

  @SerializedName("timeline")
  private Object timeline = null;

  public VaccineCountriesCoverageInner country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @Schema(description = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public VaccineCountriesCoverageInner timeline(Object timeline) {
    this.timeline = timeline;
    return this;
  }

   /**
   * Get timeline
   * @return timeline
  **/
  @Schema(description = "")
  public Object getTimeline() {
    return timeline;
  }

  public void setTimeline(Object timeline) {
    this.timeline = timeline;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaccineCountriesCoverageInner vaccineCountriesCoverageInner = (VaccineCountriesCoverageInner) o;
    return Objects.equals(this.country, vaccineCountriesCoverageInner.country) &&
        Objects.equals(this.timeline, vaccineCountriesCoverageInner.timeline);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, timeline);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaccineCountriesCoverageInner {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    timeline: ").append(toIndentedString(timeline)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
