/*
 * disease.sh Docs - An open API for disease-related statistics
 * Third Party API for reliable global disease information
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package csee.ce291_team02.Data.LmaoNinjaApiClient.generatedClient.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * Vaccines
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-02-12T19:32:54.804Z[Europe/London]")
public class Vaccines {
  @SerializedName("source")
  private String source = null;

  @SerializedName("totalCandidates")
  private String totalCandidates = null;

  @SerializedName("phases")
  private java.util.List<Phases> phases = null;

  @SerializedName("data")
  private java.util.List<Vaccine> data = null;

  public Vaccines source(String source) {
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @Schema(description = "")
  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public Vaccines totalCandidates(String totalCandidates) {
    this.totalCandidates = totalCandidates;
    return this;
  }

   /**
   * Get totalCandidates
   * @return totalCandidates
  **/
  @Schema(description = "")
  public String getTotalCandidates() {
    return totalCandidates;
  }

  public void setTotalCandidates(String totalCandidates) {
    this.totalCandidates = totalCandidates;
  }

  public Vaccines phases(java.util.List<Phases> phases) {
    this.phases = phases;
    return this;
  }

  public Vaccines addPhasesItem(Phases phasesItem) {
    if (this.phases == null) {
      this.phases = new java.util.ArrayList<>();
    }
    this.phases.add(phasesItem);
    return this;
  }

   /**
   * Get phases
   * @return phases
  **/
  @Schema(description = "")
  public java.util.List<Phases> getPhases() {
    return phases;
  }

  public void setPhases(java.util.List<Phases> phases) {
    this.phases = phases;
  }

  public Vaccines data(java.util.List<Vaccine> data) {
    this.data = data;
    return this;
  }

  public Vaccines addDataItem(Vaccine dataItem) {
    if (this.data == null) {
      this.data = new java.util.ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Get data
   * @return data
  **/
  @Schema(description = "")
  public java.util.List<Vaccine> getData() {
    return data;
  }

  public void setData(java.util.List<Vaccine> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Vaccines vaccines = (Vaccines) o;
    return Objects.equals(this.source, vaccines.source) &&
        Objects.equals(this.totalCandidates, vaccines.totalCandidates) &&
        Objects.equals(this.phases, vaccines.phases) &&
        Objects.equals(this.data, vaccines.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(source, totalCandidates, phases, data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Vaccines {\n");
    
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    totalCandidates: ").append(toIndentedString(totalCandidates)).append("\n");
    sb.append("    phases: ").append(toIndentedString(phases)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
